In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [8]:
#heart_df = pd.read_csv('/content/heart.csv')

heart_df = pd.read_csv('heart.csv')

In [9]:
heart_df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [10]:
heart_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    str
 2   ChestPainType   918 non-null    str
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    str
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    str
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    str
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), str(5)
memory usage: 97.6 KB

In [11]:
heart_df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [12]:
heart_df.describe(include='all')

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
count,918.000000,918,918,918.000000,918.000000,918.000000,918,918.000000,918,918.000000,918,918.000000
unique,NaN,2,4,NaN,NaN,NaN,3,NaN,2,NaN,3,NaN
top,NaN,M,ASY,NaN,NaN,NaN,Normal,NaN,N,NaN,Flat,NaN
freq,NaN,725,496,NaN,NaN,NaN,552,NaN,547,NaN,460,NaN
mean,53.510893,NaN,NaN,132.396514,198.799564,0.233115,NaN,136.809368,NaN,0.887364,NaN,0.553377
std,9.432617,NaN,NaN,18.514154,109.384145,0.423046,NaN,25.460334,NaN,1.066570,NaN,0.497414
min,28.000000,NaN,NaN,0.000000,0.000000,0.000000,NaN,60.000000,NaN,-2.600000,NaN,0.000000
25%,47.000000,NaN,NaN,120.000000,173.250000,0.000000,NaN,120.000000,NaN,0.000000,NaN,0.000000
50%,54.000000,NaN,NaN,130.000000,223.000000,0.000000,NaN,138.000000,NaN,0.600000,NaN,1.000000
75%,60.000000,NaN,NaN,140.000000,267.000000,0.000000,NaN,156.000000,NaN,1.500000,NaN,1.000000
max,77.000000,NaN,NaN,200.000000,603.000000,1.000000,NaN,202.000000,NaN,6.200000,NaN,1.000000

# **DATA PREPROCESSING**

In [13]:
#to get sum of null values in each column
heart_df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [14]:
#to check null value in each column
heart_df.isnull()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
913,False,False,False,False,False,False,False,False,False,False,False,False
914,False,False,False,False,False,False,False,False,False,False,False,False
915,False,False,False,False,False,False,False,False,False,False,False,False
916,False,False,False,False,False,False,False,False,False,False,False,False
917,False,False,False,False,False,False,False,False,False,False,False,False

In [15]:
#for duplicated values
heart_df.duplicated().sum()

np.int64(0)

In [16]:
#for number of univque values(in each feature)
heart_df.nunique()

Age                50
Sex                 2
ChestPainType       4
RestingBP          67
Cholesterol       222
FastingBS           2
RestingECG          3
MaxHR             119
ExerciseAngina      2
Oldpeak            53
ST_Slope            3
HeartDisease        2
dtype: int64

In [17]:
cat_col = heart_df.select_dtypes(include='object').columns

**Converting Catetgorical variables into Numeric Val**

*   SEX: M=0, F=1
*   Chest Pain Type: ATA=0, NAP=1, ASY=2, TA=3
*   Resting ECG: Normal=0, ST=1, LVH=2
*   ExerciseAngina: N=0, Y=1
*   ST_Slope: Up=0, Flat=1, Down=2

In [18]:
range(len(heart_df['ChestPainType'].unique()))

range(0, 4)

In [21]:
for col in cat_col:
    print(col)

    print(heart_df[col].unique(),
          list(range(len(heart_df[col].unique()))))

    heart_df[col].replace(
        heart_df[col].unique(),
        range(len(heart_df[col].unique())),
        inplace=True
    )

    print('*' * 90)

Sex
<ArrowStringArray>
['M', 'F']
Length: 2, dtype: str [0, 1]
******************************************************************************************
ChestPainType
<ArrowStringArray>
['ATA', 'NAP', 'ASY', 'TA']
Length: 4, dtype: str [0, 1, 2, 3]
******************************************************************************************
RestingECG
<ArrowStringArray>
['Normal', 'ST', 'LVH']
Length: 3, dtype: str [0, 1, 2]
******************************************************************************************
ExerciseAngina
<ArrowStringArray>
['N', 'Y']
Length: 2, dtype: str [0, 1]
******************************************************************************************
ST_Slope
<ArrowStringArray>
['Up', 'Flat', 'Down']
Length: 3, dtype: str [0, 1, 2]
******************************************************************************************

In [28]:
# for col in cat_col:
 # print(col)
  #print((heart_df[col].unique()), list(range(heart_df[col].unique())))
  #heart_df[col].replace((heart_df[col].unique()), range(heart_df[col].unique()), inplace= True)
  #print('*'*90)

In [22]:
heart_df['Cholesterol'].value_counts()

Cholesterol
0      172
254     11
223     10
220     10
211      9
      ...
353      1
278      1
157      1
176      1
131      1
Name: count, Length: 222, dtype: int64

**Cholestreol Can't be '0' so Imputing 0 Values with KNN Imputer**

In [23]:
np.nan

nan

In [24]:
heart_df['Cholesterol'].replace(0, np.nan, inplace=True)

0      289.0
1      180.0
2      283.0
3      214.0
4      195.0
       ...
913    264.0
914    193.0
915    131.0
916    236.0
917    175.0
Name: Cholesterol, Length: 918, dtype: float64

In [31]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in cat_col:
    heart_df[col] = le.fit_transform(heart_df[col])

In [32]:
print(heart_df.select_dtypes(include='object').columns)

Index([], dtype='str')

In [33]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
after_impute= imputer.fit_transform(heart_df)
heart_df= pd.DataFrame(after_impute, columns= heart_df.columns)

In [34]:
print(heart_df.dtypes)

Age               float64
Sex               float64
ChestPainType     float64
RestingBP         float64
Cholesterol       float64
FastingBS         float64
RestingECG        float64
MaxHR             float64
ExerciseAngina    float64
Oldpeak           float64
ST_Slope          float64
HeartDisease      float64
dtype: object

In [35]:
heart_df['Cholesterol'].isna().sum()

np.int64(0)

In [36]:
count=0
for i in heart_df['Cholesterol']:
  if i==0:
    count+=1
print(count)

172

**Same For Resting Blood Pressure**

In [37]:
from sklearn.impute import KNNImputer
heart_df['RestingBP'].replace(0, np.nan, inplace=True)

imputer = KNNImputer(n_neighbors=3)
after_impute= imputer.fit_transform(heart_df)

heart_df= pd.DataFrame(after_impute, columns= heart_df.columns)

In [38]:
heart_df['RestingBP'].unique()

array([140., 160., 130., 138., 150., 120., 110., 136., 115., 100., 124.,
       113., 125., 145., 112., 132., 118., 170., 142., 190., 135., 180.,
       108., 155., 128., 106.,  92., 200., 122.,  98., 105., 133.,  95.,
        80., 137., 185., 165., 126., 152., 116.,   0., 144., 154., 134.,
       104., 139., 131., 141., 178., 146., 158., 123., 102.,  96., 143.,
       172., 156., 114., 127., 101., 174.,  94., 148., 117., 192., 129.,
       164.])

In [39]:
heart_df['RestingBP'].isnull().sum()

np.int64(0)

**Change columns Types to Int**

In [40]:
withoutOldPeak = heart_df.columns

withoutOldPeak = withoutOldPeak.drop('Oldpeak')
heart_df[withoutOldPeak] = heart_df[withoutOldPeak].astype('int32')

In [41]:
heart_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int32
 1   Sex             918 non-null    int32
 2   ChestPainType   918 non-null    int32
 3   RestingBP       918 non-null    int32
 4   Cholesterol     918 non-null    int32
 5   FastingBS       918 non-null    int32
 6   RestingECG      918 non-null    int32
 7   MaxHR           918 non-null    int32
 8   ExerciseAngina  918 non-null    int32
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    int32
 11  HeartDisease    918 non-null    int32
dtypes: float64(1), int32(11)
memory usage: 46.7 KB

## **Data Visulaization**

In [42]:
heart_df.sample()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
736,54,1,0,122,286,0,0,116,1,3.2,1,1

In [43]:
heart_df.corr()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
Age,1.000000,0.055750,-0.077150,0.254399,-0.095282,0.198039,-0.007484,-0.382045,0.215793,0.258612,-0.268264,0.282039
Sex,0.055750,1.000000,-0.126559,0.005133,-0.200092,0.120076,0.071552,-0.189186,0.190664,0.105734,-0.150693,0.305445
ChestPainType,-0.077150,-0.126559,1.000000,-0.020647,0.067880,-0.073151,-0.072537,0.289123,-0.354727,-0.177377,0.213521,-0.386828
RestingBP,0.254399,0.005133,-0.020647,1.000000,0.100893,0.070193,0.022656,-0.112135,0.155101,0.164803,-0.075162,0.107589
Cholesterol,-0.095282,-0.200092,0.067880,0.100893,1.000000,-0.260974,-0.196544,0.235792,-0.034166,0.050148,0.111471,-0.232741
FastingBS,0.198039,0.120076,-0.073151,0.070193,-0.260974,1.000000,0.087050,-0.131438,0.060451,0.052698,-0.175774,0.267291
RestingECG,-0.007484,0.071552,-0.072537,0.022656,-0.196544,0.087050,1.000000,-0.179276,0.077500,-0.020438,-0.006778,0.057384
MaxHR,-0.382045,-0.189186,0.289123,-0.112135,0.235792,-0.131438,-0.179276,1.000000,-0.370425,-0.160691,0.343419,-0.400421
ExerciseAngina,0.215793,0.190664,-0.354727,0.155101,-0.034166,0.060451,0.077500,-0.370425,1.000000,0.408752,-0.428706,0.494282
Oldpeak,0.258612,0.105734,-0.177377,0.164803,0.050148,0.052698,-0.020438,-0.160691,0.408752,1.000000,-0.501921,0.403951
ST_Slope,-0.268264,-0.150693,0.213521,-0.075162,0.111471,-0.175774,-0.006778,0.343419,-0.428706,-0.501921,1.000000,-0.558771
HeartDisease,0.282039,0.305445,-0.386828,0.107589,-0.232741,0.267291,0.057384,-0.400421,0.494282,0.403951,-0.558771,1.000000

In [44]:
!pip install plotly

Requirement already satisfied: plotly in ./venv/lib/python3.12/site-packages (6.8.0)
Requirement already satisfied: narwhals>=1.15.1 in ./venv/lib/python3.12/site-packages (from plotly) (2.22.0)
Requirement already satisfied: packaging in ./venv/lib/python3.12/site-packages (from plotly) (26.2)

[notice] A new release of pip is available: 23.2.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [45]:
import plotly.express as px

In [46]:
heart_df.corr()['HeartDisease']

Age               0.282039
Sex               0.305445
ChestPainType    -0.386828
RestingBP         0.107589
Cholesterol      -0.232741
FastingBS         0.267291
RestingECG        0.057384
MaxHR            -0.400421
ExerciseAngina    0.494282
Oldpeak           0.403951
ST_Slope         -0.558771
HeartDisease      1.000000
Name: HeartDisease, dtype: float64

In [47]:
heart_df.corr()['HeartDisease'][:-1]

Age               0.282039
Sex               0.305445
ChestPainType    -0.386828
RestingBP         0.107589
Cholesterol      -0.232741
FastingBS         0.267291
RestingECG        0.057384
MaxHR            -0.400421
ExerciseAngina    0.494282
Oldpeak           0.403951
ST_Slope         -0.558771
Name: HeartDisease, dtype: float64

In [48]:
px.line(heart_df.corr()['HeartDisease'][:-1].sort_values())

# **Age & Heart Disease Distribution**

In [49]:
px.sunburst(heart_df, path=['HeartDisease', 'Age'])

In [50]:
px.histogram(heart_df, x='Age', color='HeartDisease')

**Percetnagae of Heart Disease data Distribution**

In [51]:
#Percetnagae of Heart Disease data Distribution

px.pie(heart_df, names='HeartDisease', title= 'Percetnagae of Heart Disease data Distribution')

# **Sex vs Heart Disease**

In [52]:
px.histogram(heart_df, x='Sex', color='HeartDisease')

**Chest Pain Type Vs Heart Disease**

In [53]:
px.histogram(heart_df, x='ChestPainType', color='HeartDisease')

**Resting BP vs Heart Disease**

In [54]:
heart_df['RestingBP'].unique()

array([140, 160, 130, 138, 150, 120, 110, 136, 115, 100, 124, 113, 125,
       145, 112, 132, 118, 170, 142, 190, 135, 180, 108, 155, 128, 106,
        92, 200, 122,  98, 105, 133,  95,  80, 137, 185, 165, 126, 152,
       116,   0, 144, 154, 134, 104, 139, 131, 141, 178, 146, 158, 123,
       102,  96, 143, 172, 156, 114, 127, 101, 174,  94, 148, 117, 192,
       129, 164], dtype=int32)

In [55]:
px.sunburst(heart_df, path=['HeartDisease', 'RestingBP'])

**Fasting Blood Sugar vs Heart Disease**

In [57]:
px.histogram(heart_df, x='FastingBS', color='HeartDisease')

**MaxHR vs Heart Disease**

In [58]:
px.sunburst(heart_df, path=['HeartDisease', 'MaxHR'])

In [59]:
px.violin(heart_df, x='HeartDisease', y='MaxHR' , color='HeartDisease')

**OldPeak Vs Heart Disease**

In [60]:
px.violin(heart_df, x='HeartDisease', y='Oldpeak' , color='HeartDisease')

**ST_Slope Vs Heart Disease**

In [61]:
px.histogram(heart_df, x='ST_Slope', color='HeartDisease')

**Exercise Angine vs Heart Disease**

In [62]:
px.histogram(heart_df, x='ExerciseAngina', color='HeartDisease')

# Model Training

In [63]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    heart_df.drop('HeartDisease', axis=1),
    heart_df['HeartDisease'],
    test_size=0.2,
    random_state=42,
    stratify=heart_df['HeartDisease']
)

In [64]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

solver = ['newton-cg', 'lbfgs', 'liblinear', 'newton-cholesky' , 'sag' , 'saga']
best_solver = ''
test_score = np.zeros(6)

for i, n in enumerate(solver):
    lr = LogisticRegression(solver=n).fit(X_train, y_train)
    test_score[i] = lr.score(X_test, y_test)
    if lr.score(X_test, y_test) == test_score.max():
        best_solver = n
print(best_solver)

lr = LogisticRegression(solver=best_solver)
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)

print(f'LogisticRegression Score: {accuracy_score(y_test, lr_pred)}')
print(classification_report(y_test, lr_pred))

newton-cholesky
LogisticRegression Score: 0.875
              precision    recall  f1-score   support

           0       0.90      0.80      0.85        82
           1       0.86      0.93      0.89       102

    accuracy                           0.88       184
   macro avg       0.88      0.87      0.87       184
weighted avg       0.88      0.88      0.87       184

In [65]:
from sklearn.svm import SVC
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score, classification_report

kernels = { 'linear':0, 'poly':0, 'rbf':0, 'sigmoid':0 }
best_kernel = ''

for i in kernels:
    svm = SVC(kernel=i).fit(X_train, y_train)
    y_hat = svm.predict(X_test)
    kernels[i] = f1_score(y_test, y_hat, average='weighted')
    if kernels[i] == max(kernels.values()):
        best_kernel = i
print(best_kernel)

svm = SVC(kernel=best_kernel)
svm.fit(X_train, y_train)
svm_pred = svm.predict(X_test)

print(f'SVM Score: {accuracy_score(y_test, svm_pred)}')
print(classification_report(y_test, svm_pred))

linear
SVM Score: 0.8641304347826086
              precision    recall  f1-score   support

           0       0.89      0.79      0.84        82
           1       0.85      0.92      0.88       102

    accuracy                           0.86       184
   macro avg       0.87      0.86      0.86       184
weighted avg       0.87      0.86      0.86       184

In [66]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, classification_report

dtree = DecisionTreeClassifier(class_weight='balanced')
param_grid = {
    'max_depth': [3,4,5,6,7,8],
    'min_samples_split': [2,3,4],
    'min_samples_leaf': [1,2,3,4],
    'random_state': [0,42]
}

grid_search = GridSearchCV(dtree, param_grid, cv=5)
grid_search.fit(X_train, y_train)

Ctree = DecisionTreeClassifier(**grid_search.best_params_, class_weight = 'balanced')
Ctree.fit(X_train, y_train)
dtc_pred = Ctree.predict(X_test)

print(f'Decision Tree Score: {accuracy_score(y_test, dtc_pred)}')
print(classification_report(y_test, dtc_pred))

Decision Tree Score: 0.8206521739130435
              precision    recall  f1-score   support

           0       0.77      0.85      0.81        82
           1       0.87      0.79      0.83       102

    accuracy                           0.82       184
   macro avg       0.82      0.82      0.82       184
weighted avg       0.83      0.82      0.82       184

In [67]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, classification_report

rfc = RandomForestClassifier()
param_grid = {
    'n_estimators': [50, 100, 150, 500],
    'max_features': ['sqrt' , 'log2' , None],
    'max_depth': [3,6,9,19],
    'max_leaf_nodes' : [3,6,9,19],
}

grid_search = GridSearchCV(rfc, param_grid)
grid_search.fit(X_train, y_train)

rfc = RandomForestClassifier(**grid_search.best_params_)
rfc.fit(X_train, y_train)
rfc_pred = rfc.predict(X_test)

print(f'Random Forest Score: {accuracy_score(y_test, rfc_pred)}')
print(classification_report(y_test, rfc_pred))

Random Forest Score: 0.875
              precision    recall  f1-score   support

           0       0.92      0.79      0.85        82
           1       0.85      0.94      0.89       102

    accuracy                           0.88       184
   macro avg       0.88      0.87      0.87       184
weighted avg       0.88      0.88      0.87       184

In [68]:
import pickle
file = open('LogisticR.pkl', 'wb')
pickle.dump(lr, file)

In [69]:

# Random Forest
with open('RandomForest.pkl', 'wb') as file:
    pickle.dump(rfc, file)

# Decision Tree
with open('DecisionTree.pkl', 'wb') as file:
    pickle.dump(Ctree, file)

# SVM
with open('SVM.pkl', 'wb') as file:
    pickle.dump(svm, file)